### PR TITLE
Add octokit pagination to listForRef/listFiles Github API calls

### PR DESCRIPTION
**Pull request by jtbeach**
See #744.

- Use the octokit pagination help for check run API call
- Noticed that the listFiles API call probably has the same issue so added pagination to that one as well

Tests:
- Unfortunately couldn't run the built-in NPM test target since I don't have access to the test repo
- Verified the shape of the data in VS Code using types
- Ran prettier/eslint

### CODE REVIEW

**Comment by jtbeach** [comment]
@tianhaoz95 Let me know what I can do here to get this one merged. I can see that there some status checks failing, presumably because this is running from a Github fork?

**Comment by tianhaoz95** [comment]
I think I messed up some CI conditions... give me a bit time, will figure it out and do a few tests.

**Comment by tianhaoz95** [comment]
It looks like fixing the forked testing requires a bit more work. For now, let me merge it into a non-master branch and do some testing there. Will try to fix fork testing following that.

**Comment by tianhaoz95** [comment]
@all-contributors please add @jtbeach for code ideas

**Comment by tianhaoz95** [comment]
@all-contributors please add @jtbeach for code ideas

**Pull request merged**
